import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { CartProvider } from "./cart/CartContex";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ContentWrapper from "./ContentWrapper";
import CategoryNavbar from "@/components/CategoryNavbar";
import { CartProvider } from "./cart/CartContex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
         <CartProvider> 
        
          <ContentWrapper>
          {/* <CategoryNavbar/> */}
            {children}
          </ContentWrapper>
             {/* <Navbar/> */}
          {/* <main className="flex-grow"> 
            {children}
          </main>
             <Footer/> */}
       </CartProvider> 
      </body>
 
    </html>
  );
}
